import{a as p,S as g,i}from"./assets/vendor-b42c18af.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function t(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=t(e);fetch(e.href,a)}})();const h="42598538-444db408f0d8256d557c709b2",L="https://pixabay.com/api/";async function m(r,n=1){const o=`${L}?key=${h}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=15`;try{const{data:e}=await p.get(o);return e}catch(e){throw new Error("Error fetching images: "+e.message)}}function y(r){const n=document.querySelector(".gallery");r.hits.forEach(t=>{const o=document.createElement("a");o.href=t.largeImageURL,o.rel="noopener noreferrer",o.classList.add("card"),o.innerHTML=`
            <img src="${t.webformatURL}" alt="${t.tags}">
            <div class="metrics">
                ${c("Likes",t.likes).outerHTML}
                ${c("Views",t.views).outerHTML}
                ${c("Comments",t.comments).outerHTML}
                ${c("Downloads",t.downloads).outerHTML}
            </div>
        `,n.appendChild(o)}),f()}function c(r,n){const t=document.createElement("div");t.classList.add("metric-container");const o=document.createElement("span");o.textContent=r,o.classList.add("metric-label"),o.style.fontWeight="bold",t.appendChild(o);const e=document.createElement("span");return e.textContent=n,e.classList.add("metric-value"),t.appendChild(e),t}function w(){const r=document.querySelector(".loading-indicator");r.textContent="Loading images, please wait...",r.style.display="block"}function d(){const r=document.querySelector(".loading-indicator");r.style.display="none"}function f(){new g(".gallery a",{captionDelay:250}).refresh()}let s=1;document.addEventListener("DOMContentLoaded",async function(){const r=document.querySelector(".search-form"),n=document.querySelector(".load-more-btn");r.addEventListener("submit",async function(e){e.preventDefault(),e.target.querySelector('input[type="text"]').value.trim(),s=1,await u()}),n.addEventListener("click",async function(){s++,await u()});const o=await m("your_default_query_here");y(o),f()});async function u(){w();const n=document.querySelector('.search-form input[type="text"]').value.trim();if(document.querySelector(".gallery"),n===""){d(),i.error({title:"Error",message:"Please enter a search query",position:"topCenter"});return}try{const t=await m(n,s);t.hits.length===0?i.warning({title:"Attention",message:"Sorry, no search results found. Please try another query.",position:"topCenter"}):(y(t),S(t.totalHits))}catch(t){console.error(t.message),i.error({title:"Error",message:"An error occurred while executing the request. Please try again.",position:"topCenter"})}finally{d(),b()}}function S(r){const n=document.querySelector(".load-more-btn");n.style.display=s*15<r?"block":"none",s*15>=r&&i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})}function b(){const r=document.querySelector(".card").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
