import{a as m,i as a,S as p}from"./assets/vendor-b42c18af.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const y="42598538-444db408f0d8256d557c709b2",g="https://pixabay.com/api/";async function h(t,o=1){const n=`${g}?key=${y}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`;try{const r=await m.get(n);if(r.status!==200)throw new Error("HTTP Error: "+r.status);return r.data}catch(r){throw new Error("Error fetching images: "+r.message)}}function L(t){const o=document.querySelector(".gallery");t.hits.forEach(e=>{const n=document.createElement("a");n.href=e.largeImageURL,n.rel="noopener noreferrer",n.classList.add("card"),n.innerHTML=`
            <img src="${e.webformatURL}" alt="${e.tags}">
            <div class="metrics">
                ${i("Likes",e.likes).outerHTML}
                ${i("Views",e.views).outerHTML}
                ${i("Comments",e.comments).outerHTML}
                ${i("Downloads",e.downloads).outerHTML}
            </div>
        `,o.appendChild(n)}),f()}function w(t,o){const e=document.querySelector(".load-more-btn");e.style.display=o*15<t?"block":"none",o*15>=t&&a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"})}function i(t,o){const e=document.createElement("div");e.classList.add("metric-container");const n=document.createElement("span");n.textContent=t,n.classList.add("metric-label"),n.style.fontWeight="bold",e.appendChild(n);const r=document.createElement("span");return r.textContent=o,r.classList.add("metric-value"),e.appendChild(r),e}function b(){const t=document.querySelector(".loading-indicator");t.textContent="Loading images, please wait...",t.style.display="block"}function d(){const t=document.querySelector(".loading-indicator");t.style.display="none"}function E(){const t=document.querySelector(".gallery");t.innerHTML=""}function f(){new p(".gallery a",{captionDelay:250}).refresh()}let c=1;document.addEventListener("DOMContentLoaded",async function(){const t=document.querySelector(".search-form"),o=document.querySelector(".load-more-btn");t.addEventListener("submit",async function(e){e.preventDefault();const n=e.target.querySelector('input[type="text"]').value.trim();c=1,await u(n,!0)}),o.addEventListener("click",async function(){c++;const e=document.querySelector('.search-form input[type="text"]').value.trim();await u(e,!1)}),f()});async function u(t,o){if(b(),o&&E(),!t){d(),a.error({title:"Error",message:"Please enter a search query",position:"topCenter"});return}try{const e=await h(t,c);e.hits.length===0?a.warning({title:"Attention",message:"Sorry, no search results found. Please try another query.",position:"topCenter"}):(L(e),w(e.totalHits,c),c*15>=e.totalHits&&a.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topCenter"}))}catch(e){console.error(e.message),a.error({title:"Error",message:"An error occurred while executing the request. Please try again.",position:"topCenter"})}finally{d(),S()}}function S(){const t=document.querySelector(".card");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
